### ISSUE TITLE
Application crashes when --commitEmail flag is not supplied

### ISSUE THREAD

**Issue by HarelM** [csMACnz/coveralls.net#55]
When all flag are in their correct place and all the data is present except --commitEmail, the application crashes (ran it from powershell) using latest stable Nuget package:

```
PS> Invoke-Expression $cmd
output file 'cov.json' already exists and will be overwritten.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at csmacnz.Coveralls.MainArgs.get_OptCommitemail() in c:\projects\coveralls-net\src\csmacnz.Coveralls\T4DocoptNet.cs:
line 84
   at csmacnz.Coveralls.CommandLineGitDataResolver.GenerateData() in c:\projects\coveralls-net\src\csmacnz.Coveralls\Com
mandLineGitDataResolver.cs:line 26
   at csmacnz.Coveralls.Program.<ResolveGitData>b__d(IGitDataResolver p) in c:\projects\coveralls-net\src\csmacnz.Covera
lls\Program.cs:line 182
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at csmacnz.Coveralls.Program.ResolveGitData(MainArgs args) in c:\projects\coveralls-net\src\csmacnz.Coveralls\Program
.cs:line 182
   at csmacnz.Coveralls.Program.Main(String[] argv) in c:\projects\coveralls-net\src\csmacnz.Coveralls\Program.cs:line 1
18
```

**Comment by csMACnz** [comment]
can you please provide a little more context? what is $cmd?

Thanks

**Comment by HarelM** [comment]
Sorry, ran it from power shell, this is my full command:
```csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken token --commitId commitid --commitBranch master --commitAuthor author --commitMessage message --jobId jobid --useRelativePaths -o cov.json```

**Comment by csMACnz** [comment]
I've had a lot of issues with the args library I'm using. which is why I'm writing my own. ill take a look at this bug in the mean-time, though.

**Comment by csMACnz** [comment]
if you look at the usage, when you provide commitauthor and commitmessage, then commitemail is also required. That is probably why it is crashing.
https://github.com/csMACnz/coveralls.net/blob/master/src/csmacnz.Coveralls/Main.usage.txt#L4

I'll take a look at providing an error over crashing though. (as I said, the args library was supposed to catch that case.)

**Comment by csMACnz** [comment]
This is/was a bug in the way docopt.net was being used, the update fixes the autogenerated code so this shouldn't be a problem anymore.
